name: Deploy Image
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/belowaverage-org/syslogmssql:latest
    - name: Login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u krisdb2009 --password-stdin
    - name: Publish the Docker image
      run: docker push ghcr.io/belowaverage-org/syslogmssql:latest
